# Using elastic results in an error during similarity search query.

---
  version: '3'
  services:
    elasticsearch:
      container_name: es01
      image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
      environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
      ports:
        - 9200:9200
      networks:
        - elastic
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536

    kibana:
      image: docker.elastic.co/kibana/kibana:8.12.2
      container_name: kib01
      environment:
        XPACK_APM_SERVICEMAPENABLED: "true"
        XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: aaaaaaaa-c4d3-4a0a-8290-2abcb83ab3aa

      ports:
        - 5601:5601
      networks:
        - elastic
    # vacation-service:



  networks:
    elastic: