server:
  servlet:
    context-path: /planner


spring:
  ai:
    openai:
      api-key: <passed from CLI>
      chat:
        options:
          # model: gpt-4o # meh
          # model: gpt-4o-mini - no significant improvement over gpt-4-0125-preview
          model: gpt-4o-2024-11-20 # - Best performance
          # model: o1-preview - does not support FC
          temperature: 0.7
      embedding:
        enabled: true
    vectorstore:
      elasticsearch:
        initialize-schema: true # This creates the index for the embeddings.
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  elasticsearch:
    uris: http://localhost:9200
#    username: elastic
#    password: changeme

logging:
  config: classpath:log4j2.xml

rag:
  topK: 5
  similarity-threshold: 0.1
  # Delete previously stored embeddings that are related to the embedding that is currently being processed?
  delete-previous-related-embeddings: true

weather:
  visualcrossing:
    url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
    apiKey: <passed from CLI>

flight:
  amadeus:
    url-root: https://test.api.amadeus.com
    url-reference-airports: ${flight.amadeus.url-root}/v1/reference-data/locations/airports
    url-shopping: ${flight.amadeus.url-root}/v2/shopping/flight-offers
    url-security: ${flight.amadeus.url-root}/v1/security/oauth2/token
    client-id: <passed from CLI>
    client-secret: <passed from CLI>

currency-exchange:
  vat-comply:
    url: https://api.vatcomply.com/rates

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'